### ISSUE TITLE
about source code

### ISSUE THREAD

**Issue by GongYanfu** [ssg-research/ad3-action-distribution-divergence-detector#1]
will you  share thwe source code for more people to do research?

**Comment by bussfromspace** [comment]
Working on it this week! Hopefully you will get the code on friday or at least next monday. Btw, if you want to get source code for the attack part, please email me to get an access.

**Comment by GongYanfu** [comment]
which email should I send message to you?

**Comment by bussfromspace** [comment]
Hi,
That's the correct mail adress. Currently I have other paper submissions and between jobs, but I will try finish the code at the end of this month. Do you also want codes related to the attack part?


Kind Regards,


Buse Gul Atli

Doctoral Candidate,  Secure Systems Research Group.

Aalto University,

Espoo, FINLAND.

________________________________

**Comment by GongYanfu** [comment]
yes，I want all of them.
thank you



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/21/2022 20:54 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [ssg-research/ad3-action-distribution-divergence-detector] about source code (Issue #1) |


Hi,
That's the correct mail adress. Currently I have other paper submissions and between jobs, but I will try finish the code at the end of this month. Do you also want codes related to the attack part?


Kind Regards,


Buse Gul Atli

Doctoral Candidate, Secure Systems Research Group.

Aalto University,

Espoo, FINLAND.

________________________________

**Comment by bussfromspace** [comment]
Hi, the code is now finalized. You can pull/fork and use for your research.
